socials:
  - label: email
    url: mailto:umejesif@gmail.com
  - label: github
    url: https://github.com/favour-umejesi
  - label: linkedin
    url: https://linkedin.com/in/favour-umejesi
  - label: medium
    url: https://medium.com/@umejesif
  - label: x
    url: https://x.com/Odalokoghene
copyright: © 2026 Favour Umejesi
